### ISSUE TITLE
Custom entity for budget

### ISSUE THREAD

**Issue by DoctorGrim** [DoctorGrim/YNAB-google-assistant#19]
Read first: https://cloud.google.com/dialogflow/docs/entities-overview

If we want to recognize category names from speech we'll need to make an entity to do so. The _entity type_, in this case, would be category-name and the _entity entries_ would be the name of those categories (e.g. groceries, electric, utilities, etc). 

Create an entity named "category-name" that includes all the default category names as entries. Ask Brady and Buffy if category name data exists so we can add other often used category names. 

Question: Will be be able to get the budget for a category who's name is not included? (ie will dialog flow recognize "how much money do I have in my X budget" if X is not an already an entry.

**Comment by rraabe** [comment]
@mjakebarrington You may have already solved this issue with the {} addition. We'll have to do more testing to know for sure.

**Comment by mjakebarrington** [comment]
As I understand it, @{categories, @sys.void}  in dialogflow combined with your search function on line 25 should cover ANY category, including categories created by the user, so long as dialogflow recognizes the user's speech and can correctly parse speech into the string to search.

**Comment by mjakebarrington** [comment]
Yes, this appears to have been resolved.

<img width="430" alt="Screen Shot 2019-08-13 at 4 15 53 PM" src="https://user-images.githubusercontent.com/51297178/62974358-0aa19480-bde6-11e9-8719-201ff9691a85.png">

**Comment by mjakebarrington** [comment]
* As a side note *
When I type, pi is a recognized budget. When I use my voice, DialogFlow assumes I meant 'pie'.

Words that sound the same but have different spellings can cause some confusion, but I doubt this is something we can/should resolve on our end. Perhaps we could add entities for common budgets that may sound comparable to something else if they exist. Admittedly, not too many people have a 'pi' budget but some people may enjoy the baked dish enough to have a 'pie' budget. I simply reversed it as an edge case.

**Comment by mjakebarrington** [comment]
Also I believe some layer is having difficulties with very large numbers. My $9,999,999,999,999.99 food budget caused a 'not responding' error. Again... edge case.
