### ISSUE TITLE
Dialogflow webhook for getting buget from YNAB

### ISSUE THREAD

**Issue by DoctorGrim** [DoctorGrim/YNAB-google-assistant#22]
Assuming the user is authorized and has selected a default budget...

Write the JS code that returns all budget category names and their balances and stores the data in an object. Return both the name and balance of the requested category from the object.

**Comment by rraabe** [comment]
Use the code below as a template. See the React web app for an example. 

`async budgetMonth() {
    const budgetMonthRequest = ynabAPI.months.getBudgetMonth(
      "default",
      "current"
    );
    budgetMonthRequest.then(r => {
      const categories = r.data.month.categories;
      const balances = categories.map(c => {
        return {
          name: c.name,
          // we need to convert the milliunits balance to a currency amount first
          balance: ynab.utils
            .convertMilliUnitsToCurrencyAmount(c.balance, 2)
            .toFixed(2),
          budgeted: ynab.utils
            .convertMilliUnitsToCurrencyAmount(c.budgeted, 2)
            .toFixed(2)
        };
      });
      console.log(balances);
    });
  }`

Example output from the console. 
`(27) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]
0: {name: "Uncategorized", balance: "0.00", budgeted: "0.00"}
1: {name: "To be Budgeted", balance: "10000.00", budgeted: "0.00"}
2: {name: "Renter's/Home Insurance", balance: "100.00", budgeted: "100.00"}
3: {name: "Computer Replacement", balance: "20.00", budgeted: "20.00"}
4: {name: "Vacation", balance: "200.00", budgeted: "200.00"}
5: {name: "Deferred Income SubCategory", balance: "0.00", budgeted: "0.00"}
6: {name: "Software Subscriptions", balance: "84.00", budgeted: "84.00"}
7: {name: "Transportation", balance: "100.00", budgeted: "100.00"}
8: {name: "Internet", balance: "65.00", budgeted: "65.00"}
9: {name: "Auto Maintenance", balance: "75.00", budgeted: "75.00"}
10: {name: "Home Maintenance", balance: "100.00", budgeted: "100.00"}
11: {name: "Gifts", balance: "50.00", budgeted: "50.00"}
12: {name: "Fitness", balance: "50.00", budgeted: "50.00"}
13: {name: "Education", balance: "100.00", budgeted: "100.00"}
14: {name: "Dining Out", balance: "200.00", budgeted: "200.00"}
15: {name: "Fun Money", balance: "600.00", budgeted: "600.00"}
16: {name: "Electric", balance: "100.00", budgeted: "100.00"}
17: {name: "Interest & Fees", balance: "20.00", budgeted: "20.00"}
18: {name: "Stuff I Forgot to Budget For", balance: "200.00", budgeted: "200.00"}
19: {name: "Water", balance: "100.00", budgeted: "100.00"}
20: {name: "Mortgage", balance: "1500.00", budgeted: "1500.00"}
21: {name: "Groceries", balance: "350.00", budgeted: "500.00"}
22: {name: "Giving", balance: "20.00", budgeted: "20.00"}
23: {name: "Clothing", balance: "100.00", budgeted: "100.00"}
24: {name: "Medical", balance: "80.00", budgeted: "80.00"}
25: {name: "Day care", balance: "2200.00", budgeted: "2200.00"}
26: {name: "Phone", balance: "53.00", budgeted: "53.00"}`
