### ISSUE TITLE
Asking for a budget that doesn't exist crashes the app

### ISSUE THREAD

**Issue by rraabe** [DoctorGrim/YNAB-google-assistant#30]
Currently, when an authorized user asks for a budget that does not exist the app crashes in the app.intent(`get budget`).

Instead, when an authorized user asks for a budget that does not exist, the assistant should tell them something along the lines of "I'm sorry I couldn't find a budget for 'X'. " And then prompt the user for follow-up ("What would you like to do?"). 

The follow-up text should be part of a follow-up intent that can be add to the original 'get budget' intent. See the Code Labs level 2 example for the follow up after the user gives a color.

**Comment by mjakebarrington** [comment]
@rraabe I assigned myself to this because I think I can fix this issue when I fix the non-alphabetic character issue (#34).
