### ISSUE TITLE
Draft a privacy policy according to YNAB specifications

### ISSUE THREAD

**Issue by mjakebarrington** [DoctorGrim/YNAB-google-assistant#4]
Create a privacy policy that meets YNAB standards.

In addition to the above terms, OAuth Applications must adhere to these requirements:

- A Privacy Policy must be in place for the application that is displayed to users and that includes the following:
- An explanation of how the data obtained through the YNAB API will he handled, stored, and secured.
- A guarantee that the data obtained through the YNAB API will not unknowingly be passed to any third-party.

**Comment by therealrico** [comment]
https://api.youneedabudget.com/#oauth-requirements

Reach out to Buffy

**Comment by therealrico** [comment]
https://developers.google.com/actions/policies/privacy-policy-guide
