### ISSUE TITLE
use token to access YNAB API

### ISSUE THREAD

**Issue by therealrico** [DoctorGrim/YNAB-google-assistant#6]
https://api.youneedabudget.com/#access-token-usage

Access Token Usage
Once you have obtained an access token, you must use HTTP Bearer Authentication, as defined in RFC6750, to authenticate when sending requests to the API. We support Authorization Request Header and URI Query Parameter as means to pass an access token.

Authorization Request Header
The recommended method for sending an access token is by using an Authorization Request Header where the access token is sent in the HTTP request header.

`curl -H "Authorization: Bearer <ACCESS_TOKEN>" https://api.youneedabudget.com/v1/budgets`

URI Query Parameter
An access token can also be passed as a URI query parameter named "access_token":

`curl https://api.youneedabudget.com/v1/budgets?access_token=<ACCESS_TOKEN>`

**Comment by bradymholt** [comment]
During our call yesterday I mentioned using the `GET /budgets/{budget_id}/categories` endpoint but I think using `GET /budgets/{budget_id}/months/{month}` might be easier to work with because the categories are wrapped in groups so it is less to parse.  Here is an example using the `ynab` package for how to get category balances:

```
const ynab = require("ynab");
const accessToken ="abc123xyz";
const ynabAPI = new ynab.API(accessToken);

 // "last-used" is a psuedo budgetId for referencing the last used budget
const budgetId = "last-used";
const month = "current"

const budgetMonthRequest = ynabAPI.months.getBudgetMonth(budgetId, month);
budgetMonthRequest.then(r => {
  const categories = r.data.month.categories;
  const balances = categories.map(c => {
    return {
      name: c.name,
      // we need to convert the milliunits balance to a currency amount first
      balance: ynab.utils
        .convertMilliUnitsToCurrencyAmount(c.balance, 2)
        .toFixed(2)
    };
  });
  console.log(balances);
  /*
    Example output:
    [
      { name: 'Medical', balance: '77.00' },
      { name: 'Fitness', balance: '4.00' },
      { name: 'Gifts', balance: '29.00' },
      { name: 'gas', balance: '15.00' },
      { name: 'Student Loan', balance: '21.00' },
      ...
    ]
  */
});
```
