### ISSUE TITLE
Get Access Token

### ISSUE THREAD

**Issue by therealrico** [DoctorGrim/YNAB-google-assistant#8]
Pass access token off too Google Actions

**Comment by bradymholt** [comment]
I played around with a test Google Action to figure out the OAuth config.

On the Account Linking page:

![image](https://user-images.githubusercontent.com/759811/62790816-7ce64200-ba91-11e9-92d9-0c1cc948d398.png)

You can fill out the info like this:

![image](https://user-images.githubusercontent.com/759811/62790784-69d37200-ba91-11e9-8cfe-32603feee04d.png)

Note the Redirect URI in particular needs to you the specific PROJECT_ID.  Details are [here](https://developers.google.com/actions/identity/oauth2) in the docs.

Hope this helps!

**Comment by rraabe** [comment]
Marshall has implemented the OAuth feature and found the access token we needed for the YNAB API stored in conv.user.raw.accessToken. A limitation exists that we have to have created an conv object to access the token this way. We can't instantiate the YNAB API before the conv object has been created.
